// <auto-generated />
using KLADobj.InfrastructureServices.Gateways.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KLADobj.WebService.Migrations
{
    [DbContext(typeof(KLADobjContext))]
    [Migration("20200601124723_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("KLADobj.DomainObjects.kladobj", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChillType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Free")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("KLADobjs");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Address = "город Москва, Манежная улица, дом 2-10, сооружение 1",
                            ChillType = "бесплатный",
                            Free = "действует",
                            Name = "Стационарный общественный туалет № 123"
                        },
                        new
                        {
                            Id = 2L,
                            Address = "город Москва, Большая Садовая улица, дом 16, сооружение 1",
                            ChillType = "бесплатный",
                            Free = "действует",
                            Name = "Стационарный общественный туалет № 45"
                        },
                        new
                        {
                            Id = 3L,
                            Address = "город Москва, улица Земляной Вал, дом 1/4, строение 1",
                            ChillType = "бесплатный",
                            Free = "действует",
                            Name = "Стационарный общественный туалет № 13"
                        },
                        new
                        {
                            Id = 4L,
                            Address = "город Москва, Марксистская улица, дом 2, строение 2",
                            ChillType = "бесплатный",
                            Free = "действует",
                            Name = "Стационарный общественный туалет № 85"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
